"""
Django settings for companyzone project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir' or os.path.join(BASE_DIR, 'subdir')
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the environment variables from the .env file
# This tells Python to look exactly in the folder where manage.py lives
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production (But now changed according to production)
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production as secret!
SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
# On your local computer, this will be True. On Render, we can turn it off safely.
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = ['*']

# INTERNAL_IPS is to identify safe, local developers 
# so the server can give them special debugging powers without exposing secrets to the public web.
# 1. Showing the Django Debug Toolbar
# 2. Revealing Technical Error Pages
# 3. Running Special Logic for Developers
# Benefits:
# Security: Restricts dangerous admin data to local machines.
# Performance: Keeps heavy development scripts off public user sessions.
# Convenience: Gives developers instant access to diagnostics automatically.
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]



# ==========================================================================
# CORS Settings - Cross-Origin Resource Sharing
# ==========================================================================
# If running locally, it defaults to your standard Vite/React server origins
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')
# Vite fallback local path

if DEBUG:
    # While developing at home, allow any source to connect for easy debugging
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # On your live Render server, lock the gates!
    # Only allow connection requests coming directly from your official Vercel shop URL
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [    # Use in Production
        FRONTEND_URL,
        'http://127.0.0.1:5173', # Vite fallback local path
    ]



# ==========================================================================
# Application definition
# ==========================================================================
INSTALLED_APPS = [
    # Cloud Storage Engines (Add these lines)
    'cloudinary_storage',
    'cloudinary',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'empapp',
    'accounts',
    'debug_toolbar',
    'api',
    'rest_framework',
    'corsheaders',
]



# ==========================================================================
# Session Settings
# ==========================================================================
# Default: Simple setups, persistence, and data consistency.
SESSION_ENGINE  = 'django.contrib.sessions.backends.db'
# Simple, local environments without a structured database.
# SESSION_ENGINE = 'django.contrib.sessions.backends.file'
# Storing session data directly on the client browser securely.
# SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'



# ==========================================================================
# Logging
# ==========================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # Configuration to write logs directly into a file
        # on free-tier of clouds likle Render we don't have this permission
        # 'file': {
        #     'level': 'INFO',
        #     'class': 'logging.FileHandler',
        #     'filename': os.path.join(BASE_DIR, 'django_performance.log'),
        #     'formatter': 'verbose',
        # },

        # Production-Grade Cloud Logging (Streaming logs directly to the Render terminal)
        # Configuration to keep displaying logs in your terminal
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler', # Streams safely directly to the terminal logs screen
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # This catches all the log entries across your entire Django application
        # The empty string means "Global Root Logger" (catches everything)
        '': {
            # 'handlers': ['console', 'file'],
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}



# ==========================================================================
# Middlewares
# ==========================================================================
MIDDLEWARE = [
    # Custom Middlewares
    'companyzone.middleware.ReqResTimeLoggingMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.LoginRequiredMiddleware', # THE NATIVE DJANGO MIDDLEWARE
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Global security guard goes here
    # 'companyzone.middleware.LoginRequiredMiddleware'
]



# ==========================================================================
# URL Configuration
# ==========================================================================
ROOT_URLCONF = 'companyzone.urls'



# ==========================================================================
# Templates settings
# ==========================================================================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'companyzone.wsgi.application'



# ==========================================================================
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# ==========================================================================


if not DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.getenv('LOCAL_DB_NAME'),
            'USER': os.getenv('LOCAL_DB_USER'),
            'PASSWORD': os.getenv('LOCAL_DB_PASSWORD'),
            'HOST': os.getenv('LOCAL_DB_HOST'),
            'PORT': os.getenv('LOCAL_DB_PORT'),
        }
    }



# ==========================================================================
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
# ==========================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# ==========================================================================
# Internationalization
# ==========================================================================
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# ==========================================================================
# Static files (CSS, JavaScript, Images)
# ==========================================================================
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# 1. The web URL prefix for static files
STATIC_URL = 'static/' #you can give any name to just display in frontend
# 2. Where Django looks for raw files during development and 
# tell production server from where it has to collect
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]

# 3. tells WhiteNoise exactly where to gather and compress all those files into 
# one single folder when your app goes live on Render/any cloud app.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Dedicated collection folder

# 4. Turn on WhiteNoise's high-speed compression engine
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'



# ==========================================================================
# PRODUCTION MEDIA STORAGE CONFIGURATION (CLOUDINARY)
# ==========================================================================
if not DEBUG:
    # Tell Django to route user files, docs, and videos directly to Cloudinary
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
    # Pull your secret keys securely from your hidden .env file
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME':os.getenv('CLOUDINARY_CLOUD_NAME'),
        'API_KEY':os.getenv('CLOUDINARY_API_KEY'),
        'API_SECRET':os.getenv('CLOUDINARY_API_SECRET')
    }

# The web URL prefix for media files
MEDIA_URL = '/media/' #you can give any name to just display in frontend
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# ==========================================================================
if not DEBUG:
    ADMIN_PATH = os.getenv('ADMIN_PATH', 'admin/') # If missing, it defaults to standard admin/
else:
    ADMIN_PATH = os.getenv('LOCAL_ADMIN_PATH', 'admin/')
AUTH_USER_MODEL = 'accounts.AppUser' # Format: 'your_app_name.ModelClassName'
# Tell Django where your login page path lives for automated route blocking
LOGIN_URL = 'login_url'
# Configure where the app users go after hitting log in/out
LOGIN_REDIRECT_URL = 'dashboard_url'
# This will override django admin app logout also so no need to use.
# LOGOUT_REDIRECT_URL = 'login_url'


# ==========================================================================
# gunicorn server not required to run your project on your local computer.
# Gunicorn (short for "Green Unicorn") is a production-ready web application server used to run Python websites like Django or Flask on the internet
# Think of it as a powerhouse translator and manager for your website when it is live.
# 1. The Intermediary (The "Translator")
# 2. Handling Multiple Users at Once (Concurrency)
# 3. Stability and Crash Protection
# On your own computer, you usually use Django's built-in development server by running python manage.py runserver.
