"""
Django settings for companyzone project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from pickle import TRUE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%^)gyqv)l%@#!#nuu4gz!vrydflxp$+=mfz*j#8n)%2g+4yh1g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = ['*']


# INTERNAL_IPS is to identify safe, local developers 
# so the server can give them special debugging powers without exposing secrets to the public web.
# 1. Showing the Django Debug Toolbar
# 2. Revealing Technical Error Pages
# 3. Running Special Logic for Developers
# Benefits:
# Security: Restricts dangerous admin data to local machines.
# Performance: Keeps heavy development scripts off public user sessions.
# Convenience: Gives developers instant access to diagnostics automatically.
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'empapp',
    'accounts',
    'debug_toolbar',
    'api',
    'rest_framework',
    'corsheaders',
]

# Default: Simple setups, persistence, and data consistency.
SESSION_ENGINE  = 'django.contrib.sessions.backends.db'
# Simple, local environments without a structured database.
# SESSION_ENGINE = 'django.contrib.sessions.backends.file'
# Storing session data directly on the client browser securely.
# SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        # Configuration to write logs directly into a file
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django_performance.log',
            'formatter': 'verbose',
        },
        # Configuration to keep displaying logs in your terminal
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # This catches all the log entries across your entire Django application
        # The empty string means "Global Root Logger" (catches everything)
        '': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    },
}

MIDDLEWARE = [
    # Custom Middlewares
    'companyzone.middleware.ReqResTimeLoggingMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.LoginRequiredMiddleware', # THE NATIVE DJANGO MIDDLEWARE
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Global security guard goes here
    # 'companyzone.middleware.LoginRequiredMiddleware'
]

CORS_ALLOW_ALL_ORIGINS = True # Only Testing
# CORS_ALLOWED_ORIGINS = [    # Use in Production
#     'http://localhost:5173',
# ]


ROOT_URLCONF = 'companyzone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'companyzone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'compzone_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


AUTH_USER_MODEL = 'accounts.AppUser' # Format: 'your_app_name.ModelClassName'
# Tell Django where your login page path lives for automated route blocking
LOGIN_URL = 'login_url'
# Configure where the app users go after hitting log in/out
LOGIN_REDIRECT_URL = 'dashboard_url'
# This will override django admin app logout also so no need to use.
# LOGOUT_REDIRECT_URL = 'login_url'