# Generated by Django 6.0.6 on 2026-06-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eno', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=30)),
                ('esal', models.IntegerField()),
                ('epfpic', models.ImageField(null=True, upload_to='profile_pics')),
                ('eintvid', models.FileField(null=True, upload_to='interview_vids')),
                ('eresume', models.FileField(null=True, upload_to='resumes')),
                ('edept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_emp', to='empapp.department')),
                ('eloc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empapp.location')),
            ],
        ),
    ]
