# Generated by Django 6.0.6 on 2026-07-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_employees', 'Can view all employees list')]},
        ),
    ]
