# Generated by Django 6.0.6 on 2026-07-25 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0003_globalpermissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalPermissions',
        ),
    ]
