# Generated by Django 6.0.6 on 2026-07-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0005_globalpermissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('view_detail_employee', 'Can view single employee detail')]},
        ),
    ]
