# Generated by Django 6.0.6 on 2026-07-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={'verbose_name': 'App User', 'verbose_name_plural': 'AppUsers'},
        ),
    ]
