# Generated by Django 6.0.6 on 2026-07-25 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_api_user',
            field=models.BooleanField(default=False, help_text='Designates whether this account belongs to an external application/API developer.'),
        ),
    ]
